CREATE SEQUENCE CASA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_CASA BEFORE
INSERT
  ON CASA FOR EACH ROW DECLARE BEGIN
SELECT
  CASA_SEQ.NEXTVAL INTO :NEW.ID_CASA
FROM
  DUAL;

END;

/ CREATE SEQUENCE COLONIA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_COLONIA BEFORE
INSERT
  ON COLONIA FOR EACH ROW DECLARE BEGIN
SELECT
  COLONIA_SEQ.NEXTVAL INTO :NEW.ID_COLONIA
FROM
  DUAL;

END;

/ CREATE SEQUENCE CONTROLPARENTAL_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_CONTROLPARENTAL BEFORE
INSERT
  ON CONTROLPARENTAL FOR EACH ROW DECLARE BEGIN
SELECT
  CONTROLPARENTAL_SEQ.NEXTVAL INTO :NEW.ID_CONTROLPARENTAL
FROM
  DUAL;

END;

/ CREATE SEQUENCE CONTROLTIPOROL_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_CONTROLTIPOROL BEFORE
INSERT
  ON CONTROLTIPOROL FOR EACH ROW DECLARE BEGIN
SELECT
  CONTROLTIPOROL_SEQ.NEXTVAL INTO :NEW.ID_CONTROLTIPOROL
FROM
  DUAL;

END;

/ CREATE SEQUENCE CP_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_CP BEFORE
INSERT
  ON CP FOR EACH ROW DECLARE BEGIN
SELECT
  CP_SEQ.NEXTVAL INTO :NEW.ID_CP
FROM
  DUAL;

END;

/ CREATE SEQUENCE DIRECCION_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_DIRECCION BEFORE
INSERT
  ON DIRECCION FOR EACH ROW DECLARE BEGIN
SELECT
  DIRECCION_SEQ.NEXTVAL INTO :NEW.ID_DIRECCION
FROM
  DUAL;

END;

/ CREATE SEQUENCE DISPOSITIVO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_DISPOSITIVO BEFORE
INSERT
  ON DISPOSITIVO FOR EACH ROW DECLARE BEGIN
SELECT
  DISPOSITIVO_SEQ.NEXTVAL INTO :NEW.ID_DISPOSITIVO
FROM
  DUAL;

END;

/ CREATE SEQUENCE ESPACIO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_ESPACIO BEFORE
INSERT
  ON ESPACIO FOR EACH ROW DECLARE BEGIN
SELECT
  ESPACIO_SEQ.NEXTVAL INTO :NEW.ID_ESPACIO
FROM
  DUAL;

END;

/ CREATE SEQUENCE LADA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_LADA BEFORE
INSERT
  ON LADA FOR EACH ROW DECLARE BEGIN
SELECT
  LADA_SEQ.NEXTVAL INTO :NEW.ID_LADA
FROM
  DUAL;

END;

/ CREATE SEQUENCE MUNICIPIO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_MUNICIPIO BEFORE
INSERT
  ON MUNICIPIO FOR EACH ROW DECLARE BEGIN
SELECT
  MUNICIPIO_SEQ.NEXTVAL INTO :NEW.ID_MUNICIPIO
FROM
  DUAL;

END;

/ CREATE SEQUENCE NOMBRE_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_NOMBRE BEFORE
INSERT
  ON NOMBRE FOR EACH ROW DECLARE BEGIN
SELECT
  NOMBRE_SEQ.NEXTVAL INTO :NEW.ID_NOMBRE
FROM
  DUAL;

END;

/ CREATE SEQUENCE PERSONA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_PERSONA BEFORE
INSERT
  ON PERSONA FOR EACH ROW DECLARE BEGIN
SELECT
  PERSONA_SEQ.NEXTVAL INTO :NEW.ID_PERSONA
FROM
  DUAL;

END;

/ CREATE SEQUENCE RED_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_RED BEFORE
INSERT
  ON RED FOR EACH ROW DECLARE BEGIN
SELECT
  RED_SEQ.NEXTVAL INTO :NEW.ID_RED
FROM
  DUAL;

END;

/ CREATE SEQUENCE REGISTROACCESO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_REGISTROACCESO BEFORE
INSERT
  ON REGISTROACCESO FOR EACH ROW DECLARE BEGIN
SELECT
  REGISTROACCESO_SEQ.NEXTVAL INTO :NEW.ID_REGISTROACCESO
FROM
  DUAL;

END;

/ CREATE SEQUENCE SENSOR_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_SENSOR BEFORE
INSERT
  ON SENSOR FOR EACH ROW DECLARE BEGIN
SELECT
  SENSOR_SEQ.NEXTVAL INTO :NEW.ID_SENSOR
FROM
  DUAL;

END;

/ CREATE SEQUENCE TELEFONO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TELEFONO BEFORE
INSERT
  ON TELEFONO FOR EACH ROW DECLARE BEGIN
SELECT
  TELEFONO_SEQ.NEXTVAL INTO :NEW.ID_TELEFONO
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOALARMA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOALARMA BEFORE
INSERT
  ON TIPOALARMA FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOALARMA_SEQ.NEXTVAL INTO :NEW.ID_TIPOALARMA
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPODISPOSITIVO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPODISPOSITIVO BEFORE
INSERT
  ON TIPODISPOSITIVO FOR EACH ROW DECLARE BEGIN
SELECT
  TIPODISPOSITIVO_SEQ.NEXTVAL INTO :NEW.ID_TIPODISPOSITIVO
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOESPACIO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOESPACIO BEFORE
INSERT
  ON TIPOESPACIO FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOESPACIO_SEQ.NEXTVAL INTO :NEW.ID_TIPOESPACIO
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOESTADO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOESTADO BEFORE
INSERT
  ON TIPOESTADO FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOESTADO_SEQ.NEXTVAL INTO :NEW.ID_TIPOESTADO
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOFOCO_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOFOCO BEFORE
INSERT
  ON TIPOFOCO FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOFOCO_SEQ.NEXTVAL INTO :NEW.ID_TIPOFOCO
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOGAS_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOGAS BEFORE
INSERT
  ON TIPOGAS FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOGAS_SEQ.NEXTVAL INTO :NEW.ID_TIPOGAS
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOHUMEDAD_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOHUMEDAD BEFORE
INSERT
  ON TIPOHUMEDAD FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOHUMEDAD_SEQ.NEXTVAL INTO :NEW.ID_TIPOHUMEDAD
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOLUZ_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOLUZ BEFORE
INSERT
  ON TIPOLUZ FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOLUZ_SEQ.NEXTVAL INTO :NEW.ID_TIPOLUZ
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOPAIS_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOPAIS BEFORE
INSERT
  ON TIPOPAIS FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOPAIS_SEQ.NEXTVAL INTO :NEW.ID_TIPOPAIS
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOPROPIEDAD_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOPROPIEDAD BEFORE
INSERT
  ON TIPOPROPIEDAD FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOPROPIEDAD_SEQ.NEXTVAL INTO :NEW.ID_TIPOPROPIEDAD
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOROL_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOROL BEFORE
INSERT
  ON TIPOROL FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOROL_SEQ.NEXTVAL INTO :NEW.ID_TIPOROL
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOSENSOR_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOSENSOR BEFORE
INSERT
  ON TIPOSENSOR FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOSENSOR_SEQ.NEXTVAL INTO :NEW.ID_TIPOSENSOR
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOSERVOMOTOR_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOSERVOMOTOR BEFORE
INSERT
  ON TIPOSERVOMOTOR FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOSERVOMOTOR_SEQ.NEXTVAL INTO :NEW.ID_TIPOSERVOMOTOR
FROM
  DUAL;

END;

/ CREATE SEQUENCE TIPOTEMPERATURA_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999999999999 MINVALUE 1 NOCACHE ORDER;

CREATE
OR REPLACE TRIGGER TIB_TIPOTEMPERATURA BEFORE
INSERT
  ON TIPOTEMPERATURA FOR EACH ROW DECLARE BEGIN
SELECT
  TIPOTEMPERATURA_SEQ.NEXTVAL INTO :NEW.ID_TIPOTEMPERATURA
FROM
  DUAL;

END;

/